export const DEPARTMENTS: string[] = [
  "Almoxarifado",
  "Ambulatório Convênio",
  "Ambulatório SUS",
  "Auditoria",
  "C.M.E.",
  "Cadastro",
  "Cardiovascular",
  "Centro Cirúrgico",
  "Clínica Cirúrgica",
  "Clínica Emília",
  "Clínica Médica",
  "Compras",
  "Contabilidade",
  "Custo Hospitalar",
  "Departamento Pessoal",
  "Endoscopia",
  "Engenharia Clínica",
  "Exames Análises Clínicas",
  "Farmácia",
  "Faturamento",
  "Financeiro",
  "Fisioterapia",
  "Gerência Integrada",
  "Gerência de Enfermagem",
  "HC Especialidades",
  "Hemodinâmica",
  "Hotelaria",
  "Informática",
  "Laboratório de Análises Clínicas",
  "Lactário",
  "Lavanderia",
  "Manutenção",
  "Maternidade SUS",
  "NIR - Núcleo Interno de Regulação",
  "Obras",
  "Ortopedia",
  "Patrimônio",
  "Pediatria",
  "Portarias",
  "Pronto Atendimento",
  "Pronto Socorro Adulto",
  "Pronto Socorro Infantil e Obstétrico",
  "Qualidade",
  "Recursos Humanos (RH)",
  "Relacionamento Externo",
  "SAME SPP",
  "SCIH",
  "Secretaria",
  "Serviço de Hemoterapia para AGT",
  "Serviço de Imagem",
  "Serviço Social",
  "Serviços de Psicologia",
  "SESMT",
  "Setor de Autorização",
  "Setor de Recursos e Glosas",
  "SND - Serviço de Nutrição e Dietética",
  "Superintendência",
  "Suprimentos",
  "Transporte",
  "UTI 01",
  "UTI 02",
  "UTI Neonatal",
  "Zeladoria",
];
