export const DEPARTMENTS: string[] = [
  "Almoxarifado",
  "Ambulatório Convênio",
  "Ambulatório de Oncologia",
  "Ambulatório SUS",
  "Auditoria Enfermagem",
  "Cadastro",
  "Capela",
  "Cardiologia",
  "C.A.S.",
  "Casa de Força",
  "Centro Cirúrgico",
  "Clínica Cirúrgica",
  "Clínica Emília",
  "Clínica Médica",
  "C.M.E.",
  "Compras",
  "Contabilidade",
  "Custo Hospitalar",
  "Emergência PS",
  "Endoscopia",
  "Engenharia Clínica",
  "Exames Análises Clínicas",
  "Exames de Anatomia Patológica",
  "Expansão / Obras",
  "Farmácia",
  "Faturamento",
  "Financeiro",
  "Fisioterapia",
  "Gerador de Energia",
  "Gerência Comercial",
  "Gerência de Processos",
  "Gerência de Enfermagem",
  "HC Especialidades",
  "Hemodinâmica",
  "Hotelaria",
  "Informática",
  "Jurídico",
  "Lactário",
  "Lavanderia",
  "Manutenção",
  "Maternidade SUS",
  "Necrotério",
  "NIR - Núcleo Interno de Regulação",
  "Ortopedia",
  "Patrimônio",
  "Pediatria",
  "Pesquisa e Desenvolvimento",
  "Portarias",
  "Pronto Atendimento",
  "Pronto Socorro Adulto",
  "Pronto Socorro Infantil",
  "Provedoria",
  "Qualidade",
  "Raio-X",
  "Reforma de Ambulatório",
  "Relacionamento Externo",
  "Recursos Humanos (RH)",
  "Sala de Videoconferência",
  "SAME SPP",
  "SCIH",
  "Secretaria",
  "Serviço de Imagem",
  "Serviço de Hemoterapia",
  "Serviço Profissional",
  "Serviço Social",
  "Serviços de Psicologia",
  "SESMT",
  "Setor de Autorização",
  "Setor de Recursos e Glosas",
  "SND - Serviço de Nutrição e Dietética",
  "Superintendência",
  "Suprimentos",
  "Telefonia",
  "Transporte",
  "Usina de Oxigênio",
  "UTI Geral",
  "UTI Neonatal",
  "UTI 01",
  "UTI 02",
  "Zeladoria",
  "Administrativo Cruzeiro",
  "Administrativo Guaratinguetá",
  "Administrativo Lorena",
  "Alojamento Médico",
  "Auditoria",
  "Baby Med",
  "Berçário",
  "Cardiovascular",
  "Clínica Internação PS",
  "Comercial Cruzeiro",
  "Comercial Guaratinguetá",
  "Comercial Lorena",
  "Contas Médicas",
  "Departamento Pessoal",
  "Diretoria",
  "Gerência Administrativa",
  "Laboratório de Análises Clínicas",
  "Obras",
  "Obras Pediatria",
  "PA COVID 19",
  "P.A. Epidemiológico",
  "Pediatria Convênio",
  "Reforma Vestiário e ADM",
  "Ressarcimento ao SUS",
  "RH Cruzeiro",
  "RH Guaratinguetá",
  "RH Lorena",
  "R.H Médicos",
  "Sala Recuperação C. Cirúrgico",
  "Salão Nobre",
  "Serviço Hemoterapia",
  "Serviços Otorrino"
];
